[versions]
slf4j-api = "2.0.7"
logback = "1.4.11"
commons-math = "3.6.1"
fits = "1.18.0"
gson = "2.10.1"
micronaut = "4.0.0-M2"
richtextfx = "0.11.1"
jcodec="0.2.5"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
commons-math = { module = "org.apache.commons:commons-math3", version.ref = "commons-math" }
fits = { module = "gov.nasa.gsfc.heasarc:nom-tam-fits", version.ref = "fits" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
richtextfx = { module = "org.fxmisc.richtext:richtextfx", version.ref = "richtextfx" }
jcodec = { module = "org.jcodec:jcodec", version.ref = "jcodec"}
