[versions]
slf4j-api = "2.0.17"
logback = "1.5.18"
commonmark = "0.24.0"
commons-compress="1.27.1"
commons-math = "3.6.1"
fits = "1.21.0"
gson = "2.13.1"
micronaut = "4.7.6"
richtextfx = "0.11.5"
jcodec="0.2.5"
ikonli="12.4.0"

[libraries]
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
commonmark = { module = "org.commonmark:commonmark", version.ref = "commonmark"}
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-math = { module = "org.apache.commons:commons-math3", version.ref = "commons-math" }
fits = { module = "gov.nasa.gsfc.heasarc:nom-tam-fits", version.ref = "fits" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
richtextfx = { module = "org.fxmisc.richtext:richtextfx", version.ref = "richtextfx" }
jcodec = { module = "org.jcodec:jcodec", version.ref = "jcodec"}
micronaut = { module = "io.micronaut.platform:micronaut-platform", version.ref = "micronaut"}
ikonli= { module = "org.kordamp.ikonli:ikonli-javafx", version.ref = "ikonli" }
ikonli-fluentui = { module = "org.kordamp.ikonli:ikonli-fluentui-pack", version.ref = "ikonli" }
